#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vd="nvim -d"

# Use $XINITRC
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# functions
xevv(){ xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'; }
hf() { tac "$HISTFILE" | fzf --no-sort | xclip -selection clipboard -r && xdotool key alt+v ;}
#cat -n -s "$HISTFILE" | fzf --tac | awk '{$1=""; print $0}' | xclip -selection clipboard -r && xdotool key alt+v
initvimplug() { curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim ;}

alias q=exit
alias v=vim
alias py=python
alias l="lsd -hA --group-dirs first"
alias bashh='bash --rcfile ~/.bash/.bashrc'
alias weath='less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport'
alias mirror="mpv /dev/video0 --profile=low-latency --untimed -vf=hflip" #--force-seekable=yes
alias vifm=vifmrun
alias myip="curl https://ipinfo.io/ip"
alias sc='sc-im'
alias pika="{ killall -q picom; sleep 0.2; picom -b ;} >/dev/null 2>&1"
alias blueon="sudo /usr/lib/bluetooth/bluetoothd -n" # bluetooth without a service
alias apagar="xset dpms force off"
#alias vf='nvim `fzf`'
#alias pipeconfig="sudoedit /usr/share/pipewire/pipewire.conf"
#alias lapon='xrandr --output LVDS1 --auto --right-of VGA1'
#alias lapoff='xrandr --output LVDS1 --off'
# templeos font (hurts my eyes)
alias stos="setsid -f st -f 'TempleOS:style=Regular:size=9:antialias=true:autohint=true'"

# Reminder: make some programs not prompt for a password when using sudo
# echo "$USER ALL=(ALL:ALL) NOPASSWD: 'PROGRAMS'" | sudo tee /etc/sudoers.d/$USER

# Auto exec with sudo
for x in \
make zzz mount umount sv rsm powertop dmesg gparted
do alias $x="sudo $x"; done; unset x

# Package managers
alias p="sudo pacman"
#alias	\
#	xq="xbps-query"	\
#	up='xbps-install -Suv'	\
#	xi='xbps-install -Sy'	\
#	xr='sudo xbps-remove -Ry'	\
#	voidcache='sudo xbps-remove -O'

# Default flags
alias cp="cp --interactive --verbose"
alias mv="mv --interactive --verbose"
alias rm="rm --interactive=once --verbose"

# Colorize commands when possible
alias ls="ls --human-readable --literal --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"

# Common options
alias \
	ka=killall \
	mkd="mkdir -pv"	 \
	yt="ytfzf -t" \
	yta="yt -x -f bestaudio/best"	\
 	sdn="sudo shutdown -h now" \
	z=zathura
	#ffmpeg="ffmpeg -hide_banner"	\
	#e=emacs \
	#yt="youtube-dl --add-metadata -i" \
	#trem="transmission-remote" \
	#YT="youtube-viewer" \
	#f="$FILE" \

# Git
alias	\
	g="git"	\
	gd="git add -A && git commit"	\
	gp="git push"			\
	gpp="{ git add -A && git commit ;} && setsid -f git push"

# Directories shortcuts (unused currently)
alias d='dirs -v | head -10'
alias 1='cd ~/Downloads/ && l'
alias 2='cd ~/Coooode/scripts/ && l'
alias 3='cd ~/Media/Pictures/ && l'
alias 4='cd ~/Media/Music/ && l'
alias 5='cd ~/Media/Videos/ && l'
alias 6='cd -1'
alias 7='cd -2'
alias 8='cd -3'
alias 9='cd -4'
#alias	mm="cd $HOME/Media/"
#alias MM="cd $HOME/Media/ && l"
#alias mi="cd $HOME/Media/Pictures"
#alias Mi="cd $HOME/Media/Pictures && l"
#alias mw="cd $HOME/Media/Pictures/Wallpapers"
#alias Mw="cd $HOME/Media/Pictures/Wallpapers && l"

# vim: syntax=sh
